// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function isValidHttpUrl(url: unknown): url is string {
  return typeof url === 'string' && /^https?:\/\//.test(url);
}

const isConfigured = isValidHttpUrl(SUPABASE_URL) && typeof SUPABASE_PUBLISHABLE_KEY === 'string' && SUPABASE_PUBLISHABLE_KEY.length > 0;

type SupabaseFunctionsOnly = Pick<SupabaseClient<Database>, 'functions'>;

export const supabase: SupabaseClient<Database> | SupabaseFunctionsOnly = isConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : ({
      functions: {
        invoke: async () => {
          throw new Error('Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env.');
        }
      }
    } as unknown as SupabaseFunctionsOnly);
